### ISSUE TITLE
Unintended Behaviour? Preview Video of Game Needed

### ISSUE THREAD

**Issue by MagusWyvern** [yeasin50/space_craft#49]
It's unclear how the game should play out in the browser, from the deployed [Github page](https://yeasin50.github.io/space_craft/#/) I fail to see how to play the game. Maybe clearer instructions could be added? 

Unless of course, this is not what the intended behaviour of the game should be like?
![image](https://user-images.githubusercontent.com/72914828/212239762-c90f3863-c678-4215-826a-13d4f62d232f.png)

**Comment by yeasin50** [comment]
Closing this as completed.
